/*
Copyright 2019 The kaamer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kcomb.proto

package kvstore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KComb struct {
	ProteinKeys          []uint32 `protobuf:"varint,1,rep,packed,name=ProteinKeys,proto3" json:"ProteinKeys,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KComb) Reset()         { *m = KComb{} }
func (m *KComb) String() string { return proto.CompactTextString(m) }
func (*KComb) ProtoMessage()    {}
func (*KComb) Descriptor() ([]byte, []int) {
	return fileDescriptor_8463a01f3b3e09c6, []int{0}
}

func (m *KComb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KComb.Unmarshal(m, b)
}
func (m *KComb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KComb.Marshal(b, m, deterministic)
}
func (m *KComb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KComb.Merge(m, src)
}
func (m *KComb) XXX_Size() int {
	return xxx_messageInfo_KComb.Size(m)
}
func (m *KComb) XXX_DiscardUnknown() {
	xxx_messageInfo_KComb.DiscardUnknown(m)
}

var xxx_messageInfo_KComb proto.InternalMessageInfo

func (m *KComb) GetProteinKeys() []uint32 {
	if m != nil {
		return m.ProteinKeys
	}
	return nil
}

func (m *KComb) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*KComb)(nil), "kvstore.KComb")
}

func init() { proto.RegisterFile("kcomb.proto", fileDescriptor_8463a01f3b3e09c6) }

var fileDescriptor_8463a01f3b3e09c6 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4e, 0xce, 0xcf,
	0x4d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x2e, 0x2b, 0x2e, 0xc9, 0x2f, 0x4a,
	0x55, 0xb2, 0xe7, 0x62, 0xf5, 0x76, 0xce, 0xcf, 0x4d, 0x12, 0x52, 0xe0, 0xe2, 0x0e, 0x28, 0xca,
	0x2f, 0x49, 0xcd, 0xcc, 0xf3, 0x4e, 0xad, 0x2c, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0d, 0x42,
	0x16, 0x12, 0x12, 0xe1, 0x62, 0x75, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0,
	0x0d, 0x82, 0x70, 0x92, 0xd8, 0xc0, 0x06, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x15, 0xa7,
	0x2b, 0x42, 0x5f, 0x00, 0x00, 0x00,
}
