// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ksettings.proto

package kvstore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KSettings struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	CreationDate         string   `protobuf:"bytes,3,opt,name=CreationDate,proto3" json:"CreationDate,omitempty"`
	OriginalFile         string   `protobuf:"bytes,4,opt,name=OriginalFile,proto3" json:"OriginalFile,omitempty"`
	DatabaseIndexed      bool     `protobuf:"varint,5,opt,name=DatabaseIndexed,proto3" json:"DatabaseIndexed,omitempty"`
	IDsIndexed           bool     `protobuf:"varint,6,opt,name=IDsIndexed,proto3" json:"IDsIndexed,omitempty"`
	NamesIndexed         bool     `protobuf:"varint,7,opt,name=NamesIndexed,proto3" json:"NamesIndexed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KSettings) Reset()         { *m = KSettings{} }
func (m *KSettings) String() string { return proto.CompactTextString(m) }
func (*KSettings) ProtoMessage()    {}
func (*KSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e477fb09697567a, []int{0}
}

func (m *KSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KSettings.Unmarshal(m, b)
}
func (m *KSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KSettings.Marshal(b, m, deterministic)
}
func (m *KSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KSettings.Merge(m, src)
}
func (m *KSettings) XXX_Size() int {
	return xxx_messageInfo_KSettings.Size(m)
}
func (m *KSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_KSettings.DiscardUnknown(m)
}

var xxx_messageInfo_KSettings proto.InternalMessageInfo

func (m *KSettings) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KSettings) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *KSettings) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

func (m *KSettings) GetOriginalFile() string {
	if m != nil {
		return m.OriginalFile
	}
	return ""
}

func (m *KSettings) GetDatabaseIndexed() bool {
	if m != nil {
		return m.DatabaseIndexed
	}
	return false
}

func (m *KSettings) GetIDsIndexed() bool {
	if m != nil {
		return m.IDsIndexed
	}
	return false
}

func (m *KSettings) GetNamesIndexed() bool {
	if m != nil {
		return m.NamesIndexed
	}
	return false
}

func init() {
	proto.RegisterType((*KSettings)(nil), "kvstore.KSettings")
}

func init() { proto.RegisterFile("ksettings.proto", fileDescriptor_4e477fb09697567a) }

var fileDescriptor_4e477fb09697567a = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcf, 0x4b, 0xaa, 0xc2, 0x30,
	0x14, 0xc6, 0x71, 0x72, 0x6f, 0x1f, 0x36, 0x08, 0x85, 0x8c, 0x32, 0x92, 0xd2, 0x51, 0x46, 0x4e,
	0x5c, 0x82, 0x45, 0x28, 0x82, 0x4a, 0x5d, 0x41, 0x4a, 0x0f, 0x25, 0xb4, 0x26, 0x92, 0x1c, 0xc4,
	0x2d, 0xbb, 0x0b, 0x49, 0x7c, 0xd0, 0x3a, 0xfb, 0xf8, 0xe7, 0x07, 0x49, 0x68, 0x3e, 0x38, 0x40,
	0x54, 0xba, 0x77, 0xeb, 0xab, 0x35, 0x68, 0x58, 0x3a, 0xdc, 0x1c, 0x1a, 0x0b, 0xe5, 0x83, 0xd0,
	0x6c, 0x7f, 0x7e, 0x1f, 0x32, 0x46, 0xa3, 0x83, 0xbc, 0x00, 0x27, 0x05, 0x11, 0x59, 0x13, 0xb6,
	0x6f, 0x27, 0x63, 0x91, 0xff, 0x15, 0x44, 0xc4, 0x4d, 0xd8, 0xac, 0xa4, 0xcb, 0xad, 0x05, 0x89,
	0xca, 0xe8, 0x4a, 0x22, 0xf0, 0xff, 0xe0, 0x67, 0xcd, 0x9b, 0xa3, 0x55, 0xbd, 0xd2, 0x72, 0xdc,
	0xa9, 0x11, 0x78, 0xf4, 0x32, 0xd3, 0xc6, 0x04, 0xcd, 0x2b, 0x89, 0xb2, 0x95, 0x0e, 0x6a, 0xdd,
	0xc1, 0x1d, 0x3a, 0x1e, 0x17, 0x44, 0x2c, 0x9a, 0xdf, 0xcc, 0x56, 0x94, 0xd6, 0x95, 0xfb, 0xa0,
	0x24, 0xa0, 0x49, 0xf1, 0xb7, 0xf9, 0xd7, 0x7e, 0x45, 0x1a, 0xc4, 0xac, 0xb5, 0x49, 0xf8, 0xfb,
	0xe6, 0x19, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x54, 0x48, 0x74, 0x0e, 0x01, 0x00, 0x00,
}
