/*
Copyright 2019 The kaamer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protein.proto

package kvstore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Protein struct {
	Entry                string   `protobuf:"bytes,1,opt,name=Entry,proto3" json:"Entry,omitempty"`
	ProteinName          string   `protobuf:"bytes,2,opt,name=ProteinName,proto3" json:"ProteinName,omitempty"`
	Organism             string   `protobuf:"bytes,3,opt,name=Organism,proto3" json:"Organism,omitempty"`
	Taxonomy             string   `protobuf:"bytes,4,opt,name=Taxonomy,proto3" json:"Taxonomy,omitempty"`
	EC                   string   `protobuf:"bytes,5,opt,name=EC,proto3" json:"EC,omitempty"`
	Sequence             string   `protobuf:"bytes,6,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Length               int32    `protobuf:"varint,7,opt,name=Length,proto3" json:"Length,omitempty"`
	GO                   []string `protobuf:"bytes,8,rep,name=GO,proto3" json:"GO,omitempty"`
	HAMAP                []string `protobuf:"bytes,9,rep,name=HAMAP,proto3" json:"HAMAP,omitempty"`
	KEGG                 []string `protobuf:"bytes,10,rep,name=KEGG,proto3" json:"KEGG,omitempty"`
	BioCyc               []string `protobuf:"bytes,11,rep,name=BioCyc,proto3" json:"BioCyc,omitempty"`
	KEGG_Pathways        []string `protobuf:"bytes,12,rep,name=KEGG_Pathways,json=KEGGPathways,proto3" json:"KEGG_Pathways,omitempty"`
	Biocyc_Pathways      []string `protobuf:"bytes,13,rep,name=Biocyc_Pathways,json=BiocycPathways,proto3" json:"Biocyc_Pathways,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Protein) Reset()         { *m = Protein{} }
func (m *Protein) String() string { return proto.CompactTextString(m) }
func (*Protein) ProtoMessage()    {}
func (*Protein) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3c3736181c33c07, []int{0}
}

func (m *Protein) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protein.Unmarshal(m, b)
}
func (m *Protein) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protein.Marshal(b, m, deterministic)
}
func (m *Protein) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protein.Merge(m, src)
}
func (m *Protein) XXX_Size() int {
	return xxx_messageInfo_Protein.Size(m)
}
func (m *Protein) XXX_DiscardUnknown() {
	xxx_messageInfo_Protein.DiscardUnknown(m)
}

var xxx_messageInfo_Protein proto.InternalMessageInfo

func (m *Protein) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func (m *Protein) GetProteinName() string {
	if m != nil {
		return m.ProteinName
	}
	return ""
}

func (m *Protein) GetOrganism() string {
	if m != nil {
		return m.Organism
	}
	return ""
}

func (m *Protein) GetTaxonomy() string {
	if m != nil {
		return m.Taxonomy
	}
	return ""
}

func (m *Protein) GetEC() string {
	if m != nil {
		return m.EC
	}
	return ""
}

func (m *Protein) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

func (m *Protein) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Protein) GetGO() []string {
	if m != nil {
		return m.GO
	}
	return nil
}

func (m *Protein) GetHAMAP() []string {
	if m != nil {
		return m.HAMAP
	}
	return nil
}

func (m *Protein) GetKEGG() []string {
	if m != nil {
		return m.KEGG
	}
	return nil
}

func (m *Protein) GetBioCyc() []string {
	if m != nil {
		return m.BioCyc
	}
	return nil
}

func (m *Protein) GetKEGG_Pathways() []string {
	if m != nil {
		return m.KEGG_Pathways
	}
	return nil
}

func (m *Protein) GetBiocyc_Pathways() []string {
	if m != nil {
		return m.Biocyc_Pathways
	}
	return nil
}

func init() {
	proto.RegisterType((*Protein)(nil), "kvstore.Protein")
}

func init() { proto.RegisterFile("protein.proto", fileDescriptor_b3c3736181c33c07) }

var fileDescriptor_b3c3736181c33c07 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4e, 0x83, 0x40,
	0x14, 0x46, 0x03, 0x2d, 0xd0, 0xde, 0x96, 0x9a, 0xdc, 0x18, 0x73, 0xe3, 0x8a, 0xe8, 0xc2, 0xae,
	0xdc, 0xf8, 0x04, 0x2d, 0x21, 0x98, 0xf8, 0x03, 0xa9, 0xee, 0x0d, 0x92, 0x49, 0x4b, 0x0c, 0x33,
	0x0a, 0xe3, 0xcf, 0x3c, 0xac, 0xef, 0x62, 0xe6, 0x0e, 0xa8, 0x2b, 0x38, 0xe7, 0x7c, 0xb9, 0x09,
	0x40, 0xfc, 0xda, 0x29, 0x2d, 0x1a, 0x79, 0x69, 0x9f, 0x0a, 0xa3, 0x97, 0x8f, 0x5e, 0xab, 0x4e,
	0x9c, 0x7d, 0xfb, 0x10, 0x95, 0x2e, 0xe1, 0x31, 0x04, 0x99, 0xd4, 0x9d, 0x21, 0x2f, 0xf1, 0xd6,
	0xf3, 0x9d, 0x03, 0x4c, 0x60, 0x31, 0x0c, 0xee, 0xab, 0x56, 0x90, 0xcf, 0xed, 0xbf, 0xc2, 0x53,
	0x98, 0x15, 0xdd, 0xbe, 0x92, 0x4d, 0xdf, 0xd2, 0x84, 0xf3, 0x2f, 0xdb, 0xf6, 0x58, 0x7d, 0x29,
	0xa9, 0x5a, 0x43, 0x53, 0xd7, 0x46, 0xc6, 0x15, 0xf8, 0x59, 0x4a, 0x01, 0x5b, 0x3f, 0x4b, 0xed,
	0xf6, 0x41, 0xbc, 0xbd, 0x0b, 0x59, 0x0b, 0x0a, 0xdd, 0x76, 0x64, 0x3c, 0x81, 0xf0, 0x56, 0xc8,
	0xbd, 0x3e, 0x50, 0x94, 0x78, 0xeb, 0x60, 0x37, 0x90, 0xbd, 0x91, 0x17, 0x34, 0x4b, 0x26, 0xf6,
	0x46, 0x5e, 0xd8, 0x6f, 0xb8, 0xde, 0xdc, 0x6d, 0x4a, 0x9a, 0xb3, 0x72, 0x80, 0x08, 0xd3, 0x9b,
	0x2c, 0xcf, 0x09, 0x58, 0xf2, 0xbb, 0xbd, 0xb8, 0x6d, 0x54, 0x6a, 0x6a, 0x5a, 0xb0, 0x1d, 0x08,
	0xcf, 0x21, 0xb6, 0xfd, 0xa9, 0xac, 0xf4, 0xe1, 0xb3, 0x32, 0x3d, 0x2d, 0x39, 0x2f, 0xad, 0x1c,
	0x1d, 0x5e, 0xc0, 0xd1, 0xb6, 0x51, 0xb5, 0xa9, 0xff, 0x66, 0x31, 0xcf, 0x56, 0x4e, 0x8f, 0xf6,
	0x39, 0xe4, 0xff, 0x7d, 0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x3d, 0x68, 0x4d, 0x80, 0x01,
	0x00, 0x00,
}
